<?xml version="1.0" encoding="utf-8"?><Database Name="HRINDESSO" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.24.91;Initial Catalog=HRINDESSO;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HRINDESSOConnectionString" Provider="System.Data.SqlClient" />
</Database>